version: "3.9"

services:
  postgres_db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    expose:
      - "5432"
    restart: always
    env_file:
      - ./.env
    profiles:
      - dev
      - prod

  django-core:
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      postgres_db:
        condition: service_healthy
    profiles:
      - dev
      - prod

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: -f locustfile.py --master -H http://django-core:8000
    depends_on:
      - django-core
    env_file:
      - ./.env
    profiles:
      - dev

  worker:
    image: locustio/locust
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: -f locustfile.py --worker --master-host locust
    depends_on:
      - locust
    env_file:
      - ./.env
    profiles:
      - dev

volumes:
  postgres_data:


networks:
  default:
    external: false
    name: credit_charge_app
