version: "3.9"

services:
  postgres_db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    expose:
      - "5432"
    restart: always
    env_file:
      - ./.env

  django-core:
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      postgres_db:
        condition: service_healthy


volumes:
  postgres_data:

networks:
  default:
    external: false
    name: credit_charge_app